"""assemble.py -- build MANUSCRIPT.md from the per-part drafts, in reading order.

Why a script: the parts are edited independently, and a hand-merged copy silently drifts. Rerun this after any part changes.
Section numbers inside the parts are per-part; the LaTeX pass renumbers. Nothing is rewritten here, only ordered.
"""
from pathlib import Path

D = Path(r'E:/Docms/无监督域适应/translated/0917')
ORDER = [
    ('Abstract, Introduction, Method', 'PAPER_DRAFT.md'),
    ('Theory', 'PAPER_THEORY.md'),
    ('Results', 'PAPER_RESULTS.md'),
    ('Discussion, Conclusion, Related work', 'PAPER_DISCUSSION.md'),
]
banner = ("<!-- Generated by assemble.py from the per-part drafts; edit the parts, not this file. -->\n\n"
          "# Cross-port SAR vessel classification with scene knowledge: order transfers, value does not\n\n"
          "*Assembled manuscript. Section numbers are per-part pending the LaTeX pass.*\n\n---\n\n")
out = [banner]
for title, fn in ORDER:
    p = D / fn
    if not p.exists():
        out.append('> MISSING: %s\n\n' % fn)
        continue
    out.append('# PART: %s  *(from %s)*\n\n' % (title, fn))
    out.append(p.read_text(encoding='utf-8').strip() + '\n\n---\n\n')
(D / 'MANUSCRIPT.md').write_text(''.join(out), encoding='utf-8')
txt = (D / 'MANUSCRIPT.md').read_text(encoding='utf-8')
print('MANUSCRIPT.md 生成 ✓ ｜ %d 字符 ｜ 各部分: %s'
      % (len(txt), ', '.join(t for t, f in ORDER if (D / f).exists())))
