#!/usr/bin/env bash
# commit + push the LaTeX pass (git direct: proxy vars would send it to a dead proxy)
set -eu
cd "E:/临时会话/repo_rsk"
cp "E:/Docms/无监督域适应/translated/0917/main.tex" "E:/Docms/无监督域适应/translated/0917/refs.bib" "E:/Docms/无监督域适应/translated/0917/main.pdf" paper/
cp "E:/Docms/无监督域适应/translated/0917/figs/make_figs.py" \
   "E:/Docms/无监督域适应/translated/0917/figs/fig2_rank_vs_value.pdf" \
   "E:/Docms/无监督域适应/translated/0917/figs/fig3_budget_and_sources.pdf" paper/figs/
export -n HTTP_PROXY HTTPS_PROXY http_proxy https_proxy ALL_PROXY all_proxy 2>/dev/null || true
unset HTTP_PROXY HTTPS_PROXY http_proxy https_proxy ALL_PROXY all_proxy 2>/dev/null || true
GIT="git -c http.proxy= -c https.proxy="
$GIT add -A
$GIT commit -q -F - <<'MSG'
LaTeX/IEEE pass: main.tex compiles to a 9-page journal draft, and every citation is a paper that exists

The markdown manuscript becomes one IEEEtran source with continuous numbering: 10 tables and 3
figures, all cross-references switched from the prose's "(Section 7)" style to \label/\ref so the
numbering survives the move. Figure 1 is TikZ; Figures 2 and 3 are generated by figs/make_figs.py
from the numbers already recorded in EXPERIMENT_STATE.md, so a number change is a one-line edit and
a rerun rather than a redrawn figure. Compile: tectonic -X compile main.tex (IEEEtran, booktabs,
tikz, hyperref; no local TeX install needed).

The Related Work section is written and cited for the first time. Every reference was resolved
against a registry or publisher page rather than recalled: Crossref DOIs for the journal work
(IEEE TGRS/JSTARS/TNNLS/TIT, Remote Sensing, Science China, Neural Computation, ESWA-style LNCS),
the official proceedings pages for the conference work (PMLR v37/v80/v97/v119, NeurIPS 2017-2021,
MLSys 2021, JMLR v17), and the arXiv API for author lists where a page did not expose them. 26
entries, no invented citation, and no citation used for a claim the cited work does not make. One
deliberate omission is recorded in the source: the earlier draft planned an "adaptive conformal"
row in the guarantee table, which would have attributed a measured realised-risk range to a method
we never ran under that name, so that row was dropped and the table keeps the three constructions
the experiments actually tested.

The author block is a placeholder, not a guess.
MSG
$GIT push 2>&1 | tail -3
$GIT log --oneline -1
